//
// Created by curo on 21.03.2024.
//

#ifndef BASICSOFPROGRAMMINGCOURSE_LABS_TESTS_H
#define BASICSOFPROGRAMMINGCOURSE_LABS_TESTS_H
void test_lab20_all();
#endif //BASICSOFPROGRAMMINGCOURSE_LABS_TESTS_H
