//
// Created by curo on 01.04.2024.
//

#ifndef BASICSOFPROGRAMMINGCOURSE_TEST_STRING_H
#define BASICSOFPROGRAMMINGCOURSE_TEST_STRING_H

void test_strings();

#endif //BASICSOFPROGRAMMINGCOURSE_TEST_STRING_H
