//
// Created by curo on 03.03.2024.
//

#ifndef BASICSOFPROGRAMMINGCOURSE_TEST_MATRIX_H
#define BASICSOFPROGRAMMINGCOURSE_TEST_MATRIX_H
void test_matrix_all();
#endif //BASICSOFPROGRAMMINGCOURSE_TEST_MATRIX_H
